# Generated by Django 4.1.5 on 2023-01-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumb',
            new_name='thumbnail',
        ),
    ]
